'use client';

import { useState } from 'react';
import Link from 'next/link';

const siteItems = [
  'Diagnóstico inicial do negócio, público e objetivos comerciais',
  'Arquitetura de páginas, navegação e organização das informações',
  'Home estratégica com proposta de valor, diferenciais e chamadas para ação',
  'Páginas de serviços, soluções, áreas de atendimento e apresentação da empresa',
  'Seção de projetos, portfólio, provas sociais e depoimentos quando disponíveis',
  'Página de contato com formulário, WhatsApp, localização e canais comerciais',
  'Layout responsivo e experiência adaptada para celular, tablet e computador',
  'Identidade visual aplicada: cores, tipografia, imagens, ícones e componentes',
  'SEO técnico inicial: títulos, descrições, estrutura semântica e indexação básica',
  'Otimização de performance, carregamento, acessibilidade e boas práticas',
  'Configuração de publicação, domínio e orientações para manutenção',
  'Testes de navegação, links, formulários e comportamento em diferentes telas',
];

const supportItems = [
  'Inventário inicial dos computadores, notebooks, servidores e periféricos',
  'Identificação de usuários, setores, prioridades e equipamentos críticos',
  'Diagnóstico de rede local, Wi-Fi, switches, roteadores e conectividade',
  'Análise básica de organização de IPs, acesso e disponibilidade dos dispositivos',
  'Manutenção preventiva e corretiva dos computadores contemplados no contrato',
  'Instalação, configuração e atualização de softwares autorizados',
  'Orientação sobre contas de usuário, permissões e boas práticas de segurança',
  'Acompanhamento de backups existentes e identificação de pontos de risco',
  'Suporte relacionado a impressoras, compartilhamentos e recursos de rede',
  'Apoio técnico em câmeras, gravadores e infraestrutura já instalada',
  'Atendimento remoto e presencial conforme disponibilidade e condições acordadas',
  'Registro de chamados, prioridades, recorrências e recomendações técnicas',
];

const exclusions = [
  'Compra de computadores, servidores, câmeras, peças e licenças',
  'Cabeamento, novos pontos de rede e obras de infraestrutura',
  'Expansões de CFTV, alarmes, controle de acesso ou Wi-Fi',
  'Serviços de terceiros, mensalidades de plataformas e hospedagens',
  'Projetos complexos de migração, segurança avançada ou desenvolvimento sob demanda',
];

const stages = [
  { id: 1, code: 'FOUNDATION', label: 'Base', title: 'Site completo + estrutura de TI', price: 'R$ 5.000,00 + R$ 1.000,00/mês', description: 'A primeira etapa entrega uma presença digital profissional e organiza o suporte técnico da operação existente.', objective: 'Criar uma base confiável para a empresa apresentar seus serviços, receber contatos e trabalhar com mais estabilidade.', deliverables: ['Site completo dentro do escopo aprovado', 'Inventário e diagnóstico inicial da estrutura de TI', 'Definição de equipamentos e limites do suporte', 'Plano inicial de prioridades e melhorias'], next: 'Aprovar o escopo, realizar o levantamento e iniciar a execução.' },
  { id: 2, code: 'ACCELERATION', label: 'Evolução', title: 'Marketing, tráfego pago e conteúdo', price: 'Contratação opcional', description: 'Com o site pronto, a comunicação pode ganhar consistência e as campanhas podem ser planejadas com objetivos claros.', objective: 'Aumentar a visibilidade e transformar acessos em oportunidades comerciais acompanháveis.', deliverables: ['Planejamento de campanhas e canais', 'Artes, vídeos e conteúdo para redes sociais', 'Tráfego pago, públicos e indicadores', 'SEO contínuo e otimizações de conversão'], next: 'Definir público, metas, canais e orçamento específico.' },
  { id: 3, code: 'SCALE', label: 'Escala', title: 'CRM, automações e inteligência artificial', price: 'Projeto separado · condição especial possível', description: 'A etapa de escala conecta marketing, atendimento, orçamento e relacionamento com processos mais organizados.', objective: 'Diminuir tarefas manuais, melhorar o acompanhamento dos contatos e gerar visão do processo comercial.', deliverables: ['Mapeamento do fluxo de atendimento', 'Escolha e configuração do CRM', 'Automações, integrações e alertas', 'Recursos de IA conforme viabilidade e escopo'], next: 'Mapear processos, integrações, licenças e requisitos.' },
];

function Checklist({ items }: { items: string[] }) { return <ul className="mt-6 grid gap-3">{items.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-white/65"><span className="text-[#FFDE00]">✦</span><span>{item}</span></li>)}</ul>; }
function Icon({ children }: { children: React.ReactNode }) { return <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-white/[.06] text-xs font-black text-[#FFDE00]">{children}</span>; }

export default function ProposalPage() {
  const [activeStage, setActiveStage] = useState(1);
  const selected = stages[activeStage - 1];
  return <main className="min-h-screen overflow-hidden bg-[#050505] text-white selection:bg-[#FFDE00] selection:text-black">
    <div className="pointer-events-none fixed inset-0 opacity-60 [background-image:linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] [background-size:64px_64px]" />
    <div className="pointer-events-none fixed -left-40 top-1/4 h-[30rem] w-[30rem] rounded-full bg-[#FFDE00]/[.07] blur-[140px]" />
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#050505]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10"><div className="flex items-center gap-3"><img src="/img/4.png" alt="Rooted" className="h-10 w-10 object-contain" /><div><p className="text-xs font-black tracking-[.28em] text-[#FFDE00]">ROOTED</p><p className="text-[9px] uppercase tracking-[.2em] text-white/35">Tecnologia & estratégia</p></div></div><nav className="hidden gap-7 text-[10px] font-black uppercase tracking-[.16em] text-white/45 md:flex"><a href="#site" className="hover:text-[#FFDE00]">Site</a><a href="#ti" className="hover:text-[#FFDE00]">TI</a><a href="#jornada" className="hover:text-[#FFDE00]">Jornada</a><a href="#investimento" className="hover:text-[#FFDE00]">Investimento</a></nav><Link href="/apresentacao" className="rounded-full border border-white/15 px-4 py-2 text-[10px] font-black uppercase tracking-wider hover:border-[#FFDE00] hover:text-[#FFDE00]">Apresentação ↗</Link></div></header>

    <section className="relative z-10 mx-auto grid min-h-[720px] max-w-7xl items-center gap-12 px-6 py-16 lg:grid-cols-[1fr_.88fr] lg:px-10 lg:py-24"><div><div className="mb-7 inline-flex rounded-full border border-[#FFDE00]/30 bg-[#FFDE00]/10 px-4 py-2 text-[10px] font-black uppercase tracking-[.2em] text-[#FFDE00]">Proposta estratégica · Ecco Cleaner</div><h1 className="max-w-4xl text-5xl font-black leading-[.92] tracking-[-.07em] sm:text-7xl lg:text-[5.4rem]">Uma estrutura<br /><span className="text-[#FFDE00]">para crescer.</span></h1><p className="mt-8 max-w-xl text-base leading-8 text-white/55 sm:text-lg">Um projeto completo de presença digital, suporte tecnológico e evolução planejada — começando pelo que a empresa precisa hoje e preparando o próximo passo.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#site" className="rounded-full bg-[#FFDE00] px-6 py-3 text-sm font-black text-black shadow-[0_0_40px_rgba(255,222,0,.18)] hover:-translate-y-1">Ver entregas ↓</a><a href="#investimento" className="rounded-full border border-white/20 px-6 py-3 text-sm font-bold hover:border-white/50">Investimento</a></div><div className="mt-14 grid max-w-xl grid-cols-3 gap-4 border-t border-white/10 pt-6"><div><b className="block text-2xl font-black sm:text-3xl">R$ 5 mil</b><span className="text-[10px] uppercase tracking-wider text-white/35">Site completo</span></div><div><b className="block text-2xl font-black sm:text-3xl">R$ 1 mil</b><span className="text-[10px] uppercase tracking-wider text-white/35">TI / mês</span></div><div><b className="block text-2xl font-black text-[#FFDE00] sm:text-3xl">03</b><span className="text-[10px] uppercase tracking-wider text-white/35">Etapas</span></div></div></div><div className="relative flex min-h-[440px] items-end justify-center lg:min-h-[610px]"><div className="absolute bottom-12 h-80 w-80 rounded-full bg-[#FFDE00]/15 blur-[110px]" /><div className="absolute bottom-8 h-[27rem] w-[27rem] rounded-full border border-[#FFDE00]/20 shadow-[0_0_120px_rgba(255,222,0,.12)]" /><div className="absolute left-0 top-10 z-20 rounded-2xl border border-white/10 bg-black/70 p-4 backdrop-blur-xl"><p className="text-[9px] font-black uppercase tracking-[.2em] text-white/35">Plano de evolução</p><p className="mt-2 text-sm font-black text-[#FFDE00]">Base → Crescimento</p></div><img src="/img/slide-1.png" alt="Mascote Rooted" className="relative z-10 max-h-[600px] w-full object-contain drop-shadow-[0_35px_60px_rgba(0,0,0,.85)] [mask-image:linear-gradient(to_bottom,black_86%,transparent)]" /></div></section>

    <section id="site" className="relative z-10 border-y border-white/10 bg-white/[.025]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-black uppercase tracking-[.25em] text-[#FFDE00]">01 / Entrega principal</p><h2 className="mt-4 max-w-5xl text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">Um site completo, pensado<br /><span className="text-white/30">para apresentar e converter.</span></h2><p className="mt-6 max-w-3xl leading-8 text-white/55">O projeto não se limita a uma página inicial. A proposta é construir uma experiência digital organizada, profissional, responsiva e preparada para receber novos contatos.</p><div className="mt-12 grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><article className="rounded-[2rem] border border-[#FFDE00]/25 bg-[#FFDE00]/[.055] p-8 lg:p-10"><div className="flex items-center justify-between gap-4"><span className="rounded-xl bg-[#FFDE00]/15 px-3 py-2 text-[10px] font-black tracking-wider text-[#FFDE00]">ESCOPO DETALHADO</span><span className="text-2xl font-black text-[#FFDE00]">R$ 5.000</span></div><h3 className="mt-8 text-3xl font-black">O que será implementado</h3><Checklist items={siteItems} /></article><aside className="rounded-[2rem] border border-white/10 bg-black/30 p-8 lg:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/35">Resultado esperado</p><h3 className="mt-4 text-2xl font-black">Presença digital profissional</h3><p className="mt-5 leading-7 text-white/55">Uma estrutura que explique claramente os serviços da empresa, facilite o contato e transmita confiança em diferentes dispositivos.</p><div className="mt-8 space-y-4 border-t border-white/10 pt-6 text-sm text-white/65"><p>✓ Navegação clara e organizada</p><p>✓ Visual alinhado à marca</p><p>✓ Estrutura preparada para evolução</p><p>✓ Testes antes da publicação</p></div></aside></div></div></section>

    <section id="ti" className="relative z-10 mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-black uppercase tracking-[.25em] text-[#FFDE00]">02 / Operação tecnológica</p><h2 className="mt-4 max-w-5xl text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">Suporte de TI com<br /><span className="text-white/30">diagnóstico e organização.</span></h2><p className="mt-6 max-w-3xl leading-8 text-white/55">O valor mensal é uma base inicial. Antes de fechar os limites definitivos, será feito um levantamento para entender quantos equipamentos existem, quais são críticos e quais atendimentos serão contemplados.</p><div className="mt-12 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><aside className="rounded-[2rem] border border-[#FFDE00]/30 bg-[#FFDE00]/[.06] p-8 lg:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#FFDE00]">Mensalidade-base</p><p className="mt-5 text-5xl font-black text-[#FFDE00]">R$ 1.000<span className="text-base text-white/45"> / mês</span></p><h3 className="mt-8 text-2xl font-black">O que será analisado</h3><div className="mt-6 space-y-4 text-sm leading-6 text-white/65"><p>• Quantidade de computadores e usuários</p><p>• Servidores, rede, Wi-Fi e câmeras</p><p>• Horários, prioridade e canais de atendimento</p><p>• Rotinas de backup e riscos existentes</p><p>• Necessidade de atendimento remoto ou presencial</p></div></aside><article className="rounded-[2rem] border border-white/10 bg-white/[.035] p-8 lg:p-10"><h3 className="text-3xl font-black">Atividades previstas</h3><Checklist items={supportItems} /></article></div><div className="mt-8 rounded-3xl border border-amber-300/20 bg-amber-300/[.05] p-6 text-sm leading-7 text-white/65"><strong className="text-amber-300">Importante:</strong> compras, peças, licenças, novas instalações, cabeamento, expansões e serviços de terceiros não estão automaticamente incluídos na mensalidade. Essas demandas serão avaliadas e aprovadas separadamente.</div></div></section>

    <section id="jornada" className="relative z-10 border-y border-white/10 bg-white/[.025]"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-black uppercase tracking-[.25em] text-[#FFDE00]">03 / Mapa de evolução</p><h2 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">Uma rota para construir,<br /><span className="text-white/30">acelerar e escalar.</span></h2><p className="mt-6 max-w-2xl leading-8 text-white/50">Selecione cada etapa para entender o objetivo, as entregas e o próximo movimento.</p><div className="mt-12 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-3">{stages.map((stage) => <button key={stage.id} type="button" onClick={() => setActiveStage(stage.id)} className={`flex w-full items-start gap-4 rounded-3xl border p-5 text-left transition ${activeStage === stage.id ? 'border-[#FFDE00]/50 bg-[#FFDE00]/[.07]' : 'border-white/10 bg-white/[.025] hover:border-white/30'}`}><Icon>0{stage.id}</Icon><span className="flex-1"><span className="text-[9px] font-black uppercase tracking-[.18em] text-[#FFDE00]">{stage.code}</span><strong className="mt-2 block text-lg leading-tight">{stage.title}</strong><span className="mt-2 block text-xs leading-5 text-white/40">{stage.description}</span></span></button>)}</div><div className="rounded-[2rem] border border-white/15 bg-[#0b0b0b] p-7 shadow-[0_30px_110px_rgba(0,0,0,.5)] sm:p-10"><span className="rounded-full border border-[#FFDE00]/30 bg-[#FFDE00]/10 px-3 py-2 text-[10px] font-black tracking-[.2em] text-[#FFDE00]">FASE 0{selected.id}</span><p className="mt-8 text-[10px] font-black uppercase tracking-[.2em] text-white/35">{selected.code}</p><h3 className="mt-3 text-3xl font-black leading-tight sm:text-5xl">{selected.title}</h3><p className="mt-5 text-sm font-black text-[#FFDE00]">{selected.price}</p><p className="mt-7 leading-8 text-white/65">{selected.description}</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-white/35">Objetivo estratégico</p><p className="mt-3 text-sm font-bold leading-6 text-white/80">{selected.objective}</p></div><h4 className="mt-8 text-[10px] font-black uppercase tracking-[.2em] text-white/35">Entregas da etapa</h4><Checklist items={selected.deliverables} /><div className="mt-8 border-t border-white/10 pt-6"><h4 className="text-[10px] font-black uppercase tracking-[.2em] text-white/35">Próximo movimento</h4><p className="mt-3 text-sm leading-6 text-white/65">{selected.next}</p></div></div></div></div></section>

    <section id="investimento" className="relative z-10 mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-black uppercase tracking-[.25em] text-[#FFDE00]">04 / Investimento e condições</p><h2 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">Começar com clareza<br /><span className="text-white/30">e evoluir por etapas.</span></h2><div className="mt-12 grid gap-6 lg:grid-cols-2"><article className="rounded-[2rem] border border-white/10 bg-white/[.04] p-8 lg:p-10"><p className="text-[10px] font-black uppercase tracking-wider text-white/35">Projeto único</p><h3 className="mt-5 text-3xl font-black">Site completo</h3><p className="mt-3 text-3xl font-black text-[#FFDE00]">R$ 5.000,00</p><p className="mt-5 leading-7 text-white/55">Desenvolvimento e implementação conforme o escopo aprovado, com estrutura responsiva, testes e publicação.</p></article><article className="rounded-[2rem] border border-[#FFDE00]/35 bg-[#FFDE00]/[.06] p-8 lg:p-10"><p className="text-[10px] font-black uppercase tracking-wider text-[#FFDE00]">Mensalidade-base</p><h3 className="mt-5 text-3xl font-black">Suporte de TI</h3><p className="mt-3 text-3xl font-black text-[#FFDE00]">R$ 1.000,00 <span className="text-base text-white/45">/ mês</span></p><p className="mt-5 leading-7 text-white/55">Valor inicial sujeito à confirmação do inventário, quantidade de ativos, limites e condições de atendimento.</p></article></div><div className="mt-8 rounded-3xl border border-white/10 bg-white/[.025] p-7"><h3 className="text-xl font-black">Itens com orçamento separado</h3><Checklist items={exclusions} /></div></div>

    <section className="relative z-10 border-t border-white/10 bg-gradient-to-b from-white/[.04] to-transparent"><div className="mx-auto max-w-7xl px-6 py-28 lg:px-10"><p className="text-xs font-black uppercase tracking-[.25em] text-[#FFDE00]">Visão de longo prazo</p><h2 className="mt-5 max-w-5xl text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-7xl">Primeiro, uma base confiável.<br /><span className="text-[#FFDE00]">Depois, crescimento com método.</span></h2><p className="mt-8 max-w-2xl leading-8 text-white/55">Site e suporte formam o início da parceria. Marketing, conteúdo, tráfego pago, SEO e CRM poderão ser contratados em fases futuras, com escopo, investimento e aprovação próprios.</p><Link href="/apresentacao" className="mt-10 inline-flex rounded-full bg-[#FFDE00] px-6 py-3 text-sm font-black text-black hover:-translate-y-1">Conhecer a visão completa ↗</Link></div></section><footer className="relative z-10 border-t border-white/10 px-6 py-8 text-center text-[10px] font-black uppercase tracking-[.2em] text-white/25">Rooted Tecnologia • Proposta comercial Ecco Cleaner</footer>
  </main>;
}
